export default {
    "actuarial": "Actuarial",
    "open_source": "Open Source",
    "tagline": "A community of actuaries and developers building open source actuarial software.",
    "open_source_by_actuaries": "Open source software by actuaries",
    "stars_forks_update": "The stars and forks update automatically every two minutes.",
    "join_us": "Join Us",
    "education": "Education",
    // Quotes
    "what_people_say": "What people are saying about open source",
    "quote1": "Open source is about collaborating; not competing.",
    "quote1_author": "Kelsey Hightower, principal engineer for Google Cloud",
    "quote2": "In real open source, you have the right to control your own destiny.",
    "quote2_author": "Linus Torvalds, creator of Linux",
    "quote3": "Certainly there's a phenomenon around open source. You know free software will be a vibrant area. There will be a lot of neat things that get done there.",
    "quote3_author": "Bill Gates, founder of Microsoft",
    "quote4": "Once open source gets good enough, competing with it would be insane.",
    "quote4_author": "Larry Ellison, founder of Oracle",
    "quote5": "Empowerment of individuals is a key part of what makes open source work, since in the end, innovations tend to come from small groups, not from large, structured efforts.",
    "quote5_author": "Tim O'Reilly, founder of O'Reilly Media",
    "quote6": "Microsoft was on the wrong side of history when open source exploded at the beginning of the century ... The good news is that, if life is long enough, you can learn that you need to change.",
    "quote6_author": "Brad Smith, Microsoft's president and vice chair",  
}
